// Generated by scripts/gen_sfx.mjs. Do not edit by hand.
// Maps a sound-effect key to its public URL(s) and loop flag.
// Multiple URLs = numbered variant clips (<key>_1.mp3, <key>_2.mp3 ...).
export interface SfxEntry { urls: string[]; loop: boolean }
export const SFX_CLIPS: Record<string, SfxEntry> =
{
  "amb_birds": {
    "urls": [
      "/audio/sfx/amb_birds.mp3"
    ],
    "loop": true
  },
  "amb_campfire": {
    "urls": [
      "/audio/sfx/amb_campfire.mp3"
    ],
    "loop": true
  },
  "amb_dungeon": {
    "urls": [
      "/audio/sfx/amb_dungeon.mp3"
    ],
    "loop": true
  },
  "amb_forge": {
    "urls": [
      "/audio/sfx/amb_forge.mp3"
    ],
    "loop": true
  },
  "amb_rain": {
    "urls": [
      "/audio/sfx/amb_rain.mp3"
    ],
    "loop": true
  },
  "amb_snow": {
    "urls": [
      "/audio/sfx/amb_snow.mp3"
    ],
    "loop": true
  },
  "amb_water": {
    "urls": [
      "/audio/sfx/amb_water.mp3"
    ],
    "loop": true
  },
  "amb_wind_marsh": {
    "urls": [
      "/audio/sfx/amb_wind_marsh.mp3"
    ],
    "loop": true
  },
  "amb_wind_peaks": {
    "urls": [
      "/audio/sfx/amb_wind_peaks.mp3"
    ],
    "loop": true
  },
  "amb_wind_vale": {
    "urls": [
      "/audio/sfx/amb_wind_vale.mp3"
    ],
    "loop": true
  },
  "buff_apply": {
    "urls": [
      "/audio/sfx/buff_apply.mp3"
    ],
    "loop": false
  },
  "cast_arcane": {
    "urls": [
      "/audio/sfx/cast_arcane.mp3"
    ],
    "loop": true
  },
  "cast_fire": {
    "urls": [
      "/audio/sfx/cast_fire.mp3"
    ],
    "loop": true
  },
  "cast_frost": {
    "urls": [
      "/audio/sfx/cast_frost.mp3"
    ],
    "loop": true
  },
  "cast_holy": {
    "urls": [
      "/audio/sfx/cast_holy.mp3"
    ],
    "loop": true
  },
  "cast_lightning_bolt": {
    "urls": [
      "/audio/sfx/cast_lightning_bolt.wav"
    ],
    "loop": true
  },
  "cast_nature": {
    "urls": [
      "/audio/sfx/cast_nature.mp3"
    ],
    "loop": true
  },
  "cast_shadow": {
    "urls": [
      "/audio/sfx/cast_shadow.mp3"
    ],
    "loop": true
  },
  "combat_block": {
    "urls": [
      "/audio/sfx/combat_block.mp3"
    ],
    "loop": false
  },
  "combat_crit": {
    "urls": [
      "/audio/sfx/combat_crit.mp3"
    ],
    "loop": false
  },
  "combat_dodge": {
    "urls": [
      "/audio/sfx/combat_dodge.mp3"
    ],
    "loop": false
  },
  "combat_parry": {
    "urls": [
      "/audio/sfx/combat_parry.mp3"
    ],
    "loop": false
  },
  "debuff_apply": {
    "urls": [
      "/audio/sfx/debuff_apply.mp3"
    ],
    "loop": false
  },
  "foot_dirt": {
    "urls": [
      "/audio/sfx/foot_dirt.mp3"
    ],
    "loop": false
  },
  "foot_grass": {
    "urls": [
      "/audio/sfx/foot_grass.mp3"
    ],
    "loop": false
  },
  "foot_snow": {
    "urls": [
      "/audio/sfx/foot_snow.mp3"
    ],
    "loop": false
  },
  "foot_stone": {
    "urls": [
      "/audio/sfx/foot_stone.mp3"
    ],
    "loop": false
  },
  "foot_water": {
    "urls": [
      "/audio/sfx/foot_water.mp3"
    ],
    "loop": false
  },
  "foot_wood": {
    "urls": [
      "/audio/sfx/foot_wood.mp3"
    ],
    "loop": false
  },
  "heal_impact": {
    "urls": [
      "/audio/sfx/heal_impact.mp3"
    ],
    "loop": false
  },
  "impact_arcane": {
    "urls": [
      "/audio/sfx/impact_arcane.mp3"
    ],
    "loop": false
  },
  "impact_bone": {
    "urls": [
      "/audio/sfx/impact_bone.mp3"
    ],
    "loop": false
  },
  "impact_fire": {
    "urls": [
      "/audio/sfx/impact_fire.mp3"
    ],
    "loop": false
  },
  "impact_flesh": {
    "urls": [
      "/audio/sfx/impact_flesh.mp3"
    ],
    "loop": false
  },
  "impact_frost": {
    "urls": [
      "/audio/sfx/impact_frost.mp3"
    ],
    "loop": false
  },
  "impact_holy": {
    "urls": [
      "/audio/sfx/impact_holy.mp3"
    ],
    "loop": false
  },
  "impact_leather": {
    "urls": [
      "/audio/sfx/impact_leather.mp3"
    ],
    "loop": false
  },
  "impact_metal": {
    "urls": [
      "/audio/sfx/impact_metal.mp3"
    ],
    "loop": false
  },
  "impact_nature": {
    "urls": [
      "/audio/sfx/impact_nature.mp3"
    ],
    "loop": false
  },
  "impact_shadow": {
    "urls": [
      "/audio/sfx/impact_shadow.mp3"
    ],
    "loop": false
  },
  "lockpick_advanced_1": {
    "urls": [
      "/audio/sfx/lockpick_advanced_1.mp3"
    ],
    "loop": false
  },
  "lockpick_advanced_2": {
    "urls": [
      "/audio/sfx/lockpick_advanced_2.mp3"
    ],
    "loop": false
  },
  "lockpick_advanced_3": {
    "urls": [
      "/audio/sfx/lockpick_advanced_3.mp3"
    ],
    "loop": false
  },
  "lockpick_advanced_4": {
    "urls": [
      "/audio/sfx/lockpick_advanced_4.mp3"
    ],
    "loop": false
  },
  "lockpick_begin": {
    "urls": [
      "/audio/sfx/lockpick_begin.mp3"
    ],
    "loop": false
  },
  "lockpick_bind": {
    "urls": [
      "/audio/sfx/lockpick_bind.mp3"
    ],
    "loop": false
  },
  "lockpick_bonus": {
    "urls": [
      "/audio/sfx/lockpick_bonus.mp3"
    ],
    "loop": false
  },
  "lockpick_end": {
    "urls": [
      "/audio/sfx/lockpick_end.mp3"
    ],
    "loop": false
  },
  "lockpick_fail": {
    "urls": [
      "/audio/sfx/lockpick_fail.mp3"
    ],
    "loop": false
  },
  "lockpick_page_cleared": {
    "urls": [
      "/audio/sfx/lockpick_page_cleared.mp3"
    ],
    "loop": false
  },
  "lockpick_retry": {
    "urls": [
      "/audio/sfx/lockpick_retry.mp3"
    ],
    "loop": false
  },
  "lockpick_slip": {
    "urls": [
      "/audio/sfx/lockpick_slip.mp3"
    ],
    "loop": false
  },
  "lockpick_success": {
    "urls": [
      "/audio/sfx/lockpick_success.mp3"
    ],
    "loop": false
  },
  "lockpick_trap": {
    "urls": [
      "/audio/sfx/lockpick_trap.mp3"
    ],
    "loop": false
  },
  "melee_bow": {
    "urls": [
      "/audio/sfx/melee_bow.mp3"
    ],
    "loop": false
  },
  "melee_swing_blade": {
    "urls": [
      "/audio/sfx/melee_swing_blade.mp3"
    ],
    "loop": false
  },
  "melee_swing_heavy": {
    "urls": [
      "/audio/sfx/melee_swing_heavy.mp3"
    ],
    "loop": false
  },
  "melee_swing_light": {
    "urls": [
      "/audio/sfx/melee_swing_light.mp3"
    ],
    "loop": false
  },
  "melee_unarmed": {
    "urls": [
      "/audio/sfx/melee_unarmed.mp3"
    ],
    "loop": false
  },
  "mob_beast_aggro": {
    "urls": [
      "/audio/sfx/mob_beast_aggro.mp3"
    ],
    "loop": false
  },
  "mob_beast_attack": {
    "urls": [
      "/audio/sfx/mob_beast_attack.mp3"
    ],
    "loop": false
  },
  "mob_beast_death": {
    "urls": [
      "/audio/sfx/mob_beast_death.mp3"
    ],
    "loop": false
  },
  "mob_boar_aggro": {
    "urls": [
      "/audio/sfx/mob_boar_aggro.mp3"
    ],
    "loop": false
  },
  "mob_boar_attack": {
    "urls": [
      "/audio/sfx/mob_boar_attack.mp3"
    ],
    "loop": false
  },
  "mob_boar_death": {
    "urls": [
      "/audio/sfx/mob_boar_death.mp3"
    ],
    "loop": false
  },
  "mob_burrower_aggro": {
    "urls": [
      "/audio/sfx/mob_burrower_aggro.mp3"
    ],
    "loop": false
  },
  "mob_burrower_attack": {
    "urls": [
      "/audio/sfx/mob_burrower_attack.mp3"
    ],
    "loop": false
  },
  "mob_burrower_death": {
    "urls": [
      "/audio/sfx/mob_burrower_death.mp3"
    ],
    "loop": false
  },
  "mob_demon_aggro": {
    "urls": [
      "/audio/sfx/mob_demon_aggro.mp3"
    ],
    "loop": false
  },
  "mob_demon_attack": {
    "urls": [
      "/audio/sfx/mob_demon_attack.mp3"
    ],
    "loop": false
  },
  "mob_demon_death": {
    "urls": [
      "/audio/sfx/mob_demon_death.mp3"
    ],
    "loop": false
  },
  "mob_dragonkin_aggro": {
    "urls": [
      "/audio/sfx/mob_dragonkin_aggro.mp3"
    ],
    "loop": false
  },
  "mob_dragonkin_attack": {
    "urls": [
      "/audio/sfx/mob_dragonkin_attack.mp3"
    ],
    "loop": false
  },
  "mob_dragonkin_death": {
    "urls": [
      "/audio/sfx/mob_dragonkin_death.mp3"
    ],
    "loop": false
  },
  "mob_elemental_aggro": {
    "urls": [
      "/audio/sfx/mob_elemental_aggro.mp3"
    ],
    "loop": false
  },
  "mob_elemental_attack": {
    "urls": [
      "/audio/sfx/mob_elemental_attack.mp3"
    ],
    "loop": false
  },
  "mob_elemental_death": {
    "urls": [
      "/audio/sfx/mob_elemental_death.mp3"
    ],
    "loop": false
  },
  "mob_humanoid_aggro": {
    "urls": [
      "/audio/sfx/mob_humanoid_aggro.mp3"
    ],
    "loop": false
  },
  "mob_humanoid_attack": {
    "urls": [
      "/audio/sfx/mob_humanoid_attack.mp3"
    ],
    "loop": false
  },
  "mob_humanoid_death": {
    "urls": [
      "/audio/sfx/mob_humanoid_death.mp3"
    ],
    "loop": false
  },
  "mob_mudfin_aggro": {
    "urls": [
      "/audio/sfx/mob_mudfin_aggro.mp3"
    ],
    "loop": false
  },
  "mob_mudfin_attack": {
    "urls": [
      "/audio/sfx/mob_mudfin_attack.mp3"
    ],
    "loop": false
  },
  "mob_mudfin_death": {
    "urls": [
      "/audio/sfx/mob_mudfin_death.mp3"
    ],
    "loop": false
  },
  "mob_ogre_aggro": {
    "urls": [
      "/audio/sfx/mob_ogre_aggro.mp3"
    ],
    "loop": false
  },
  "mob_ogre_attack": {
    "urls": [
      "/audio/sfx/mob_ogre_attack.mp3"
    ],
    "loop": false
  },
  "mob_ogre_death": {
    "urls": [
      "/audio/sfx/mob_ogre_death.mp3"
    ],
    "loop": false
  },
  "mob_spider_aggro": {
    "urls": [
      "/audio/sfx/mob_spider_aggro.mp3"
    ],
    "loop": false
  },
  "mob_spider_attack": {
    "urls": [
      "/audio/sfx/mob_spider_attack.mp3"
    ],
    "loop": false
  },
  "mob_spider_death": {
    "urls": [
      "/audio/sfx/mob_spider_death.mp3"
    ],
    "loop": false
  },
  "mob_troll_aggro": {
    "urls": [
      "/audio/sfx/mob_troll_aggro.mp3"
    ],
    "loop": false
  },
  "mob_troll_attack": {
    "urls": [
      "/audio/sfx/mob_troll_attack.mp3"
    ],
    "loop": false
  },
  "mob_troll_death": {
    "urls": [
      "/audio/sfx/mob_troll_death.mp3"
    ],
    "loop": false
  },
  "mob_undead_aggro": {
    "urls": [
      "/audio/sfx/mob_undead_aggro.mp3"
    ],
    "loop": false
  },
  "mob_undead_attack": {
    "urls": [
      "/audio/sfx/mob_undead_attack.mp3"
    ],
    "loop": false
  },
  "mob_undead_death": {
    "urls": [
      "/audio/sfx/mob_undead_death.mp3"
    ],
    "loop": false
  },
  "move_jump": {
    "urls": [
      "/audio/sfx/move_jump.mp3"
    ],
    "loop": false
  },
  "move_land": {
    "urls": [
      "/audio/sfx/move_land.mp3"
    ],
    "loop": false
  },
  "move_splash": {
    "urls": [
      "/audio/sfx/move_splash.mp3"
    ],
    "loop": false
  },
  "move_swim": {
    "urls": [
      "/audio/sfx/move_swim.mp3"
    ],
    "loop": false
  },
  "player_death": {
    "urls": [
      "/audio/sfx/player_death.mp3"
    ],
    "loop": false
  },
  "player_hurt": {
    "urls": [
      "/audio/sfx/player_hurt.mp3"
    ],
    "loop": false
  },
  "proj_arcane": {
    "urls": [
      "/audio/sfx/proj_arcane.mp3"
    ],
    "loop": false
  },
  "proj_fire": {
    "urls": [
      "/audio/sfx/proj_fire.mp3"
    ],
    "loop": false
  },
  "proj_frost": {
    "urls": [
      "/audio/sfx/proj_frost.mp3"
    ],
    "loop": false
  },
  "proj_holy": {
    "urls": [
      "/audio/sfx/proj_holy.mp3"
    ],
    "loop": false
  },
  "proj_nature": {
    "urls": [
      "/audio/sfx/proj_nature.mp3"
    ],
    "loop": false
  },
  "proj_shadow": {
    "urls": [
      "/audio/sfx/proj_shadow.mp3"
    ],
    "loop": false
  },
  "quest_accept": {
    "urls": [
      "/audio/sfx/quest_accept.mp3"
    ],
    "loop": false
  },
  "quest_complete": {
    "urls": [
      "/audio/sfx/quest_complete.mp3"
    ],
    "loop": false
  },
  "quest_ready": {
    "urls": [
      "/audio/sfx/quest_ready.mp3"
    ],
    "loop": false
  },
  "spell_nova": {
    "urls": [
      "/audio/sfx/spell_nova.mp3"
    ],
    "loop": false
  }
} as const;
