import puppeteer from 'puppeteer-core';
import { BROWSER_PATH as EDGE } from './scripts/browser_path.mjs';
const Q='(pointer: coarse) and (max-width: 940px), (pointer: coarse) and (max-height: 760px)';
const browser = await puppeteer.launch({ executablePath: EDGE, headless: 'new', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader'], defaultViewport: { width: 880, height: 412, hasTouch:true } });
const page = await browser.newPage();
await page.evaluateOnNewDocument(() => { const real = window.matchMedia.bind(window); window.matchMedia = (q)=>(/coarse/.test(q)?{matches:true,media:q,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){},onchange:null,dispatchEvent:()=>false}:real(q)); });
await page.goto('http://localhost:5173', { waitUntil: 'networkidle0' });
await page.click('#btn-offline'); await new Promise(r=>setTimeout(r,300));
await page.type('#char-name','Tapper');
await page.click('#offline-select .mini-class[data-class="warrior"]');
await page.click('#btn-start-offline'); await new Promise(r=>setTimeout(r,3000));
console.log('fullQ:', await page.evaluate((q)=>window.matchMedia(q).matches, Q));
console.log('patched?', await page.evaluate(()=>String(window.matchMedia).slice(0,40)));
await browser.close();
