import puppeteer from 'puppeteer-core';
import { BROWSER_PATH as EDGE } from './scripts/browser_path.mjs';
const browser = await puppeteer.launch({ executablePath: EDGE, headless: 'new', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader'], defaultViewport: { width: 880, height: 412, hasTouch:true } });
const page = await browser.newPage();
await page.evaluateOnNewDocument(() => { const real = window.matchMedia.bind(window); window.matchMedia = (q)=>(/coarse/.test(q)?{matches:true,media:q,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){},onchange:null,dispatchEvent:()=>false}:real(q)); });
await page.goto('http://localhost:5173', { waitUntil: 'networkidle0' });
await page.click('#btn-offline'); await new Promise(r=>setTimeout(r,300));
await page.type('#char-name','Tapper');
await page.click('#offline-select .mini-class[data-class="warrior"]');
await page.click('#btn-start-offline'); await new Promise(r=>setTimeout(r,3000));
console.log('isPhone:', await page.evaluate(()=>window.matchMedia('(pointer: coarse) and (max-width: 940px)').matches));
await page.evaluate(()=>window.__game?.hud?.toggleOptionsMenu?.());
await new Promise(r=>setTimeout(r,300));
await page.evaluate(()=>{const g=[...document.querySelectorAll('#options-menu .btn')].find(b=>/graphics/i.test(b.textContent||''));g?.click();});
await new Promise(r=>setTimeout(r,400));
console.log('rows:', await page.evaluate(()=>[...document.querySelectorAll('#options-menu .set-row .set-name')].map(b=>b.textContent)));
await browser.close();
