// Manifest builder extracted from gen_sfx.mjs so it can be imported by tests
// without triggering gen_sfx.mjs's top-level API-key / process.exit logic.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

// Preference order when probing a bare key (no numbered variants).
// MP3 first so generated ElevenLabs clips are found without hitting disk for
// every other extension; WAV/FLAC next so custom lossless recordings survive a
// manifest rebuild without being silently dropped.
const PROBE_EXTS = ['.mp3', '.wav', '.flac', '.ogg'];

/**
 * Rebuild the SFX manifest from the files actually on disk.
 *
 * For each catalog entry the builder looks for:
 *   1. Numbered MP3 variants: <key>_1.mp3, <key>_2.mp3, ... (generated clips)
 *   2. A bare file in any supported extension: <key>.mp3, <key>.wav, ...
 *
 * This means a custom recording committed as a non-MP3 file is not silently
 * dropped when the manifest is regenerated.
 *
 * @param {Array<{key: string, loop?: boolean}>} catalog
 * @param {string} sfxDir  absolute path to the sfx asset directory
 * @param {string} manifestPath  absolute path to write the .ts manifest
 * @returns {{ count: number, errors: string[] }}
 */
export function buildManifest(catalog, sfxDir, manifestPath) {
  const entries = {};
  const errors = [];

  for (const entry of catalog) {
    const urls = [];

    // Numbered variants (always MP3, generated by ElevenLabs via gen_sfx.mjs).
    for (let i = 1; existsSync(path.join(sfxDir, `${entry.key}_${i}.mp3`)); i++) {
      urls.push(`/audio/sfx/${entry.key}_${i}.mp3`);
    }

    // Bare key: probe extensions so custom recordings in non-MP3 formats survive.
    if (urls.length === 0) {
      for (const ext of PROBE_EXTS) {
        if (existsSync(path.join(sfxDir, `${entry.key}${ext}`))) {
          urls.push(`/audio/sfx/${entry.key}${ext}`);
          break;
        }
      }
    }

    if (urls.length > 0) entries[entry.key] = { urls, loop: !!entry.loop };
  }

  const sorted = Object.fromEntries(
    Object.keys(entries)
      .sort()
      .map((k) => [k, entries[k]]),
  );
  mkdirSync(path.dirname(manifestPath), { recursive: true });
  writeFileSync(
    manifestPath,
    [
      '// Generated by scripts/gen_sfx.mjs. Do not edit by hand.',
      '// Maps a sound-effect key to its public URL(s) and loop flag.',
      '// Multiple URLs = numbered variant clips (<key>_1.mp3, <key>_2.mp3 ...).',
      'export interface SfxEntry { urls: string[]; loop: boolean }',
      'export const SFX_CLIPS: Record<string, SfxEntry> =',
      `${JSON.stringify(sorted, null, 2)} as const;`,
      '',
    ].join('\n'),
  );

  return { count: Object.keys(sorted).length, errors };
}
