import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import {
  buildVisualThemeCatalog,
  collectMissingVisualThemeTargetWarnings,
  type GeneratedVisualThemeCatalog,
  isVisualThemeCatalogFresh,
  serializeVisualThemeCatalog,
  type VisualThemeSpecFile,
} from '../scripts/lib/visual_theme_manifest.mjs';

const cliPath = fileURLToPath(
  new URL('../scripts/build_visual_theme_manifest.mjs', import.meta.url),
);
const tempRoots: string[] = [];

function specFile(name: string, spec: unknown): VisualThemeSpecFile {
  return { name, source: JSON.stringify(spec) };
}

function themeSpec(
  replacements: ReadonlyArray<Readonly<{ from: unknown; to: unknown }>>,
  items: unknown = replacements.map((row) => ({ out: row.to })),
): unknown {
  return { visualTheme: 'emberwood', replacements, items };
}

function tempRoot(): string {
  const root = mkdtempSync(path.join(tmpdir(), 'woc_visual_theme_'));
  tempRoots.push(root);
  return root;
}

afterEach(() => {
  for (const root of tempRoots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('visual theme manifest builder', () => {
  it('builds and serializes successful multi-file input deterministically', () => {
    const alpha = specFile(
      'a.json',
      themeSpec([
        {
          from: 'models/props/arch.glb',
          to: 'models/emberwood/eastbrook/arch.glb',
        },
      ]),
    );
    const zulu = specFile(
      'z.json',
      themeSpec([
        {
          from: 'ui/skills/warrior/attack.webp',
          to: 'ui/emberwood/skills/warrior/attack.webp',
        },
      ]),
    );

    const forward = serializeVisualThemeCatalog(buildVisualThemeCatalog([alpha, zulu]));
    const reversed = serializeVisualThemeCatalog(buildVisualThemeCatalog([zulu, alpha]));

    expect(reversed).toBe(forward);
    expect(forward.indexOf('models/props/arch.glb')).toBeLessThan(
      forward.indexOf('ui/skills/warrior/attack.webp'),
    );
    expect(forward).toContain('export const VISUAL_THEME_CATALOG = {');
  });

  it('emits the stable empty catalog when no spec declares a visual theme', () => {
    const catalog = buildVisualThemeCatalog([specFile('props.json', { items: [] })]);

    expect(serializeVisualThemeCatalog(catalog)).toBe(
      '// Generated by scripts/build_visual_theme_manifest.mjs. Do not edit by hand.\n' +
        'export const VISUAL_THEME_CATALOG = {} as const;\n',
    );
  });

  it('rejects duplicate logical replacements across files', () => {
    const row = {
      from: 'models/props/house.glb',
      to: 'models/emberwood/eastbrook/house.glb',
    };

    expect(() =>
      buildVisualThemeCatalog([
        specFile('a.json', themeSpec([row])),
        specFile('b.json', themeSpec([row])),
      ]),
    ).toThrow('b.json: duplicate replacement models/props/house.glb');
  });

  it.each([
    ['classic', 'classic'],
    ['typo', 'emberwod'],
    ['empty', ''],
    ['non-string', 42],
  ])('rejects the unsupported %s visual theme', (_label, visualTheme) => {
    expect(() =>
      buildVisualThemeCatalog([
        specFile('theme.json', { visualTheme, replacements: [], items: [] }),
      ]),
    ).toThrow('theme.json: unsupported visualTheme');
  });

  it.each([
    ['missing replacements', { visualTheme: 'emberwood', items: [] }],
    ['non-array replacements', { visualTheme: 'emberwood', replacements: {}, items: [] }],
    ['missing items', { visualTheme: 'emberwood', replacements: [] }],
    ['non-array items', { visualTheme: 'emberwood', replacements: [], items: {} }],
    ['non-object replacement', { visualTheme: 'emberwood', replacements: [null], items: [] }],
    [
      'non-object item',
      themeSpec([{ from: 'models/props/house.glb', to: 'models/emberwood/house.glb' }], [null]),
    ],
  ])('rejects malformed theme fixture: %s', (_label, fixture) => {
    expect(() => buildVisualThemeCatalog([specFile('bad.json', fixture)])).toThrow('bad.json:');
  });

  it('rejects malformed JSON and targets not produced by items', () => {
    expect(() => buildVisualThemeCatalog([{ name: 'broken.json', source: '{' }])).toThrow(
      'broken.json: invalid JSON',
    );
    expect(() =>
      buildVisualThemeCatalog([
        specFile(
          'missing-item.json',
          themeSpec(
            [
              {
                from: 'models/props/house.glb',
                to: 'models/emberwood/eastbrook/house.glb',
              },
            ],
            [],
          ),
        ),
      ]),
    ).toThrow('is not produced by items[]');
  });

  it('rejects non-canonical and unsafe from/to paths', () => {
    const invalidPaths = [
      '',
      '/absolute.glb',
      'models\\house.glb',
      'models//house.glb',
      'models/./house.glb',
      'models/../house.glb',
      'models/house.glb?variant=1',
      'models/house.glb#mesh',
      'https://example.com/house.glb',
      'models/https://example.com/house.glb',
      'data:model/gltf-binary;base64,AAAA',
      ' models/house.glb',
      'models/house.glb ',
    ];
    const validFrom = 'models/props/house.glb';
    const validTo = 'models/emberwood/eastbrook/house.glb';

    for (const invalid of invalidPaths) {
      expect(() =>
        buildVisualThemeCatalog([
          specFile('bad-from.json', themeSpec([{ from: invalid, to: validTo }])),
        ]),
      ).toThrow('bad-from.json: replacement.from');
      expect(() =>
        buildVisualThemeCatalog([
          specFile('bad-to.json', themeSpec([{ from: validFrom, to: invalid }])),
        ]),
      ).toThrow('bad-to.json: replacement.to');
    }
  });

  it('rejects reserved prototype path segments without rejecting safe inherited names', () => {
    for (const reserved of ['__proto__', 'prototype', 'constructor']) {
      expect(() =>
        buildVisualThemeCatalog([
          specFile('reserved.json', themeSpec([{ from: `models/${reserved}/x`, to: 'safe/x' }])),
        ]),
      ).toThrow('reserved path segment');
      expect(() =>
        buildVisualThemeCatalog([
          specFile('reserved.json', themeSpec([{ from: 'safe/x', to: `models/${reserved}/x` }])),
        ]),
      ).toThrow('reserved path segment');
    }

    const catalog = buildVisualThemeCatalog([
      specFile('safe.json', themeSpec([{ from: 'toString', to: 'safe/toString' }])),
    ]);
    expect(Object.hasOwn(catalog.emberwood ?? {}, 'toString')).toBe(true);
    expect(catalog.emberwood?.toString).toBe('safe/toString');
  });

  it('checks containment before existence and reports missing targets as warnings', () => {
    let existenceChecks = 0;
    const escaped = {
      emberwood: { 'models/props/house.glb': '../outside.glb' },
    } satisfies GeneratedVisualThemeCatalog;

    expect(() =>
      collectMissingVisualThemeTargetWarnings(escaped, '/repo/public', () => {
        existenceChecks += 1;
        return false;
      }),
    ).toThrow('target');
    expect(existenceChecks).toBe(0);

    const catalog = buildVisualThemeCatalog([
      specFile(
        'valid.json',
        themeSpec([
          { from: 'models/a.glb', to: 'models/emberwood/a.glb' },
          { from: 'models/b.glb', to: 'models/emberwood/b.glb' },
        ]),
      ),
    ]);
    const seen: string[] = [];
    const warnings = collectMissingVisualThemeTargetWarnings(catalog, '/repo/public', (target) => {
      seen.push(target);
      return target.endsWith('/a.glb');
    });

    expect(seen).toEqual([
      path.resolve('/repo/public/models/emberwood/a.glb'),
      path.resolve('/repo/public/models/emberwood/b.glb'),
    ]);
    expect(warnings).toEqual([
      '[visual-theme] emberwood target not built yet: models/emberwood/b.glb',
    ]);
  });

  it('distinguishes fresh and stale serialized catalogs', () => {
    const generated = serializeVisualThemeCatalog(buildVisualThemeCatalog([]));
    expect(isVisualThemeCatalogFresh(generated, generated)).toBe(true);
    expect(isVisualThemeCatalogFresh(`${generated}\n`, generated)).toBe(false);
  });
});

describe('visual theme manifest CLI', () => {
  it('fails check mode without rewriting stale output, then generates and verifies it', () => {
    const root = tempRoot();
    const specsDir = path.join(root, 'scripts/assets/specs');
    const srcDir = path.join(root, 'src');
    mkdirSync(specsDir, { recursive: true });
    mkdirSync(srcDir, { recursive: true });
    mkdirSync(path.join(root, 'public'), { recursive: true });
    writeFileSync(
      path.join(specsDir, 'emberwood.json'),
      JSON.stringify(
        themeSpec([
          {
            from: 'models/props/house.glb',
            to: 'models/emberwood/eastbrook/house.glb',
          },
        ]),
      ),
    );
    const output = path.join(srcDir, 'visual_theme_catalog.generated.ts');
    writeFileSync(output, 'stale catalog\n');

    const stale = spawnSync(process.execPath, [cliPath, '--check'], {
      cwd: root,
      encoding: 'utf8',
    });
    expect(stale.status).toBe(1);
    expect(stale.stderr).toContain('is stale; run npm run assets:theme-manifest');
    expect(readFileSync(output, 'utf8')).toBe('stale catalog\n');

    const generated = spawnSync(process.execPath, [cliPath], { cwd: root, encoding: 'utf8' });
    expect(generated.status).toBe(0);
    expect(readFileSync(output, 'utf8')).toContain('models/emberwood/eastbrook/house.glb');

    const fresh = spawnSync(process.execPath, [cliPath, '--check'], {
      cwd: root,
      encoding: 'utf8',
    });
    expect(fresh.status).toBe(0);
    expect(fresh.stdout).toContain('verified src/visual_theme_catalog.generated.ts');
  });

  it('keeps freshness checks ahead of generation in test and typecheck lifecycles', () => {
    const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
    expect(pkg.scripts['check:ts']).toMatch(/^npm run assets:theme-manifest:check &&/);
    expect(pkg.scripts.pretest).toMatch(
      /^npm run assets:theme-manifest:check && npm run assets:theme-manifest &&/,
    );
    expect(pkg.scripts.build).toMatch(/^npm run assets:theme-manifest &&/);
  });
});
