import path from 'node:path';

const REPLACEABLE_THEME = 'emberwood';
const RESERVED_PATH_SEGMENTS = new Set(['__proto__', 'prototype', 'constructor']);
const URL_SCHEME = /^[A-Za-z][A-Za-z0-9+.-]*:/;

function specError(name, message) {
  throw new Error(`${name}: ${message}`);
}

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function logicalPath(value, name, field) {
  if (typeof value !== 'string' || value.length === 0) {
    specError(name, `${field} must be a non-empty logical path`);
  }
  if (value !== value.trim()) specError(name, `${field} must not have surrounding whitespace`);
  if (value.startsWith('/')) specError(name, `${field} must be relative`);
  if (value.includes('\\')) specError(name, `${field} must use POSIX separators`);
  if (value.includes('?') || value.includes('#')) {
    specError(name, `${field} must not contain a query or fragment`);
  }
  if (URL_SCHEME.test(value) || value.includes('://')) {
    specError(name, `${field} must not be a URL or scheme`);
  }
  if (
    [...value].some((character) => {
      const code = character.charCodeAt(0);
      return code <= 31 || code === 127;
    })
  ) {
    specError(name, `${field} must not contain control characters`);
  }

  const segments = value.split('/');
  if (segments.some((segment) => segment === '' || segment === '.' || segment === '..')) {
    specError(name, `${field} must not contain empty, dot, or dot-dot segments`);
  }
  if (segments.some((segment) => RESERVED_PATH_SEGMENTS.has(segment))) {
    specError(name, `${field} contains a reserved path segment`);
  }
  if (path.posix.normalize(value) !== value) {
    specError(name, `${field} must be a canonical POSIX-relative path`);
  }
  return value;
}

function parseSpecFile(file) {
  let spec;
  try {
    spec = JSON.parse(file.source);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    specError(file.name, `invalid JSON: ${detail}`);
  }
  if (!isRecord(spec)) specError(file.name, 'spec must be a JSON object');
  return spec;
}

export function buildVisualThemeCatalog(files) {
  const replacements = Object.create(null);

  for (const file of [...files].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))) {
    const spec = parseSpecFile(file);
    if (!Object.hasOwn(spec, 'visualTheme')) continue;
    if (spec.visualTheme !== REPLACEABLE_THEME) {
      specError(file.name, `unsupported visualTheme ${JSON.stringify(spec.visualTheme)}`);
    }
    if (!Array.isArray(spec.replacements)) {
      specError(file.name, 'visualTheme specs require replacements[]');
    }
    if (!Array.isArray(spec.items)) {
      specError(file.name, 'visualTheme specs require items[]');
    }

    for (const row of spec.replacements) {
      if (!isRecord(row)) specError(file.name, 'replacement must be an object');
      const from = logicalPath(row.from, file.name, 'replacement.from');
      const to = logicalPath(row.to, file.name, 'replacement.to');
      if (Object.hasOwn(replacements, from)) {
        specError(file.name, `duplicate replacement ${from}`);
      }
      const item = spec.items.find(
        (entry) => isRecord(entry) && Object.hasOwn(entry, 'out') && entry.out === to,
      );
      if (!item) specError(file.name, `${to} is not produced by items[]`);
      replacements[from] = to;
    }
  }

  const catalog = Object.create(null);
  const logicalPaths = Object.keys(replacements).sort();
  if (logicalPaths.length > 0) {
    const theme = Object.create(null);
    for (const from of logicalPaths) theme[from] = replacements[from];
    catalog[REPLACEABLE_THEME] = theme;
  }
  return catalog;
}

export function serializeVisualThemeCatalog(catalog) {
  return (
    '// Generated by scripts/build_visual_theme_manifest.mjs. Do not edit by hand.\n' +
    `export const VISUAL_THEME_CATALOG = ${JSON.stringify(catalog, null, 2)} as const;\n`
  );
}

export function resolveVisualThemeTarget(publicDir, target) {
  const logical = logicalPath(target, '[visual-theme catalog]', 'target');
  const publicRoot = path.resolve(publicDir);
  const resolved = path.resolve(publicRoot, ...logical.split('/'));
  const relative = path.relative(publicRoot, resolved);
  if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error(`[visual-theme catalog]: target escapes public/: ${target}`);
  }
  return resolved;
}

export function collectMissingVisualThemeTargetWarnings(catalog, publicDir, targetExists) {
  const warnings = [];
  for (const theme of Object.keys(catalog).sort()) {
    if (theme !== REPLACEABLE_THEME) {
      throw new Error(`[visual-theme catalog]: unsupported theme ${JSON.stringify(theme)}`);
    }
    const entries = catalog[theme];
    if (!isRecord(entries)) {
      throw new Error(`[visual-theme catalog]: ${theme} replacements must be an object`);
    }
    for (const from of Object.keys(entries).sort()) {
      logicalPath(from, '[visual-theme catalog]', 'replacement.from');
      const target = entries[from];
      const resolved = resolveVisualThemeTarget(publicDir, target);
      if (!targetExists(resolved)) {
        warnings.push(`[visual-theme] ${theme} target not built yet: ${target}`);
      }
    }
  }
  return warnings;
}

export function isVisualThemeCatalogFresh(actual, expected) {
  return actual === expected;
}
