import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const specsDir = path.join(root, 'scripts/assets/specs');
const out = path.join(root, 'src/visual_theme_catalog.generated.ts');
const catalog = {};

for (const name of readdirSync(specsDir)
  .filter((file) => file.endsWith('.json'))
  .sort()) {
  const spec = JSON.parse(readFileSync(path.join(specsDir, name), 'utf8'));
  if (!spec.visualTheme) continue;
  if (!Array.isArray(spec.replacements)) {
    throw new Error(`${name}: visualTheme specs require replacements[]`);
  }
  catalog[spec.visualTheme] ??= {};
  const theme = catalog[spec.visualTheme];
  for (const row of spec.replacements) {
    if (!row.from || !row.to) throw new Error(`${name}: replacement needs from/to`);
    if (theme[row.from]) throw new Error(`${name}: duplicate replacement ${row.from}`);
    const item = spec.items.find((entry) => entry.out === row.to);
    if (!item) throw new Error(`${name}: ${row.to} is not produced by items[]`);
    theme[row.from] = row.to;
  }
}

for (const [theme, entries] of Object.entries(catalog)) {
  for (const target of Object.values(entries)) {
    if (!existsSync(path.join(root, 'public', target))) {
      console.warn(`[visual-theme] ${theme} target not built yet: ${target}`);
    }
  }
}

writeFileSync(
  out,
  `// Generated by scripts/build_visual_theme_manifest.mjs. Do not edit by hand.\n` +
    `export const VISUAL_THEME_CATALOG = ${JSON.stringify(catalog, null, 2)} as const;\n`,
);
console.log(`generated ${path.relative(root, out)}`);
