// WARFARE gear sold by FURY, the Honor Quartermaster. Every item is a
// level-20 epic sourced at level 22, so the item-level index reads it as item
// level 28 after the epic +6 quality bump.
//
// Every piece weights its stat budget toward WARFARE: primary stats are 60% of the
// slot budget (see item_budget.ts), and the freed budget is expressed as the piece's
// full WARFARE ratings (which still mirror the FULL slot budget, driving the 16.8%
// full-set target). Armor mitigation and weapon DPS, the slot's inherent baseline,
// are kept at the ilvl-28 curve. The net effect: PvP gear is a PvP-first, stat-light
// kit that never out-stats same-tier PvE gear in PvE (where its WARFARE rating is
// dead), while still winning in PvP through the WARFARE rating. In particular a PvP
// ring/amulet never out-stats the ilvl-26 PvE badge jewelry from the Heroic
// Quartermaster. The budget rule + the badge-comparison guard live in
// tests/pvp_honor_gear.test.ts.

import type { ItemDef, NpcDef } from '../types';

export const FURY_NPC_ID = 'fury';
// Reserved so adding FURY does not shift the deterministic nextId sequence used
// by every existing world spawn and parity replay.
export const FURY_ENTITY_ID = 1_000_000_001;
export const WARFARE_SOURCE_LEVEL = 22;

export const WARFARE_ITEMS: Record<string, ItemDef> = {
  // Furyforged Battlegear: Strength and Stamina mail.
  furyforged_warhelm: {
    id: 'furyforged_warhelm',
    name: 'Furyforged Warhelm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 265, str: 4, sta: 6 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_warspaulders: {
    id: 'furyforged_warspaulders',
    name: 'Furyforged Warspaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 220, str: 4, sta: 5 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_warplate: {
    id: 'furyforged_warplate',
    name: 'Furyforged Warplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 305, str: 5, sta: 7 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_girdle: {
    id: 'furyforged_girdle',
    name: 'Furyforged Girdle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, str: 3, sta: 5 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_legguards: {
    id: 'furyforged_legguards',
    name: 'Furyforged Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 285, str: 5, sta: 6 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_gauntlets: {
    id: 'furyforged_gauntlets',
    name: 'Furyforged Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, str: 3, sta: 5 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_sabatons: {
    id: 'furyforged_sabatons',
    name: 'Furyforged Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 190, str: 4, sta: 4 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Stormbound Vestments: Intellect, Stamina, and Spirit mail.
  stormbound_crown: {
    id: 'stormbound_crown',
    name: 'Stormbound Crown',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 265, int: 5, sta: 3, spi: 2 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_spaulders: {
    id: 'stormbound_spaulders',
    name: 'Stormbound Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 220, int: 4, sta: 3, spi: 2 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_hauberk: {
    id: 'stormbound_hauberk',
    name: 'Stormbound Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 305, int: 6, sta: 4, spi: 2 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_waistguard: {
    id: 'stormbound_waistguard',
    name: 'Stormbound Waistguard',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, int: 3, sta: 3, spi: 2 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_legmail: {
    id: 'stormbound_legmail',
    name: 'Stormbound Legmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 285, int: 5, sta: 4, spi: 2 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_handguards: {
    id: 'stormbound_handguards',
    name: 'Stormbound Handguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, int: 3, sta: 3, spi: 2 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_greaves: {
    id: 'stormbound_greaves',
    name: 'Stormbound Greaves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 190, int: 4, sta: 2, spi: 2 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Ashstalker Kit: Agility and Stamina leather.
  ashstalker_cowl: {
    id: 'ashstalker_cowl',
    name: 'Ashstalker Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 5, sta: 5 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_shoulderguards: {
    id: 'ashstalker_shoulderguards',
    name: 'Ashstalker Shoulderguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 4, sta: 5 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_harness: {
    id: 'ashstalker_harness',
    name: 'Ashstalker Harness',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 155, agi: 5, sta: 7 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_waistband: {
    id: 'ashstalker_waistband',
    name: 'Ashstalker Waistband',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, agi: 3, sta: 5 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_legguards: {
    id: 'ashstalker_legguards',
    name: 'Ashstalker Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 120, agi: 5, sta: 6 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_grips: {
    id: 'ashstalker_grips',
    name: 'Ashstalker Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, agi: 3, sta: 5 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_treads: {
    id: 'ashstalker_treads',
    name: 'Ashstalker Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 85, agi: 4, sta: 4 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Cinderweave Regalia: Intellect, Stamina, and Spirit cloth.
  cinderweave_cowl: {
    id: 'cinderweave_cowl',
    name: 'Cinderweave Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 70, int: 5, sta: 3, spi: 2 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_mantle: {
    id: 'cinderweave_mantle',
    name: 'Cinderweave Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 50, int: 4, sta: 3, spi: 2 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_raiment: {
    id: 'cinderweave_raiment',
    name: 'Cinderweave Raiment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 6, sta: 4, spi: 2 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_cord: {
    id: 'cinderweave_cord',
    name: 'Cinderweave Cord',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 45, int: 3, sta: 3, spi: 2 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_legwraps: {
    id: 'cinderweave_legwraps',
    name: 'Cinderweave Legwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 65, int: 5, sta: 4, spi: 2 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_handwraps: {
    id: 'cinderweave_handwraps',
    name: 'Cinderweave Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 45, int: 3, sta: 3, spi: 2 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_slippers: {
    id: 'cinderweave_slippers',
    name: 'Cinderweave Slippers',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 40, int: 4, sta: 2, spi: 2 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Necklaces: one Strength, one Agility, and one caster profile.
  final_oath_medallion: {
    id: 'final_oath_medallion',
    name: 'Medallion of the Final Oath',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 4, sta: 4 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 225,
    sellValue: 0,
    soulbound: true,
  },
  razorwind_torque: {
    id: 'razorwind_torque',
    name: 'Razorwind Torque',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 4, sta: 4 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 225,
    sellValue: 0,
    soulbound: true,
  },
  cinder_sigil_pendant: {
    id: 'cinder_sigil_pendant',
    name: 'Cinder-Sigil Pendant',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 4, sta: 3, spi: 1 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 225,
    sellValue: 0,
    soulbound: true,
  },

  // Rings: two distinct choices for each role profile.
  iron_vow_band: {
    id: 'iron_vow_band',
    name: 'Iron Vow Band',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 3, sta: 4 },
    pvpOffenseRating: 12,
    pvpDefenseRating: 12,
    priceHonor: 150,
    sellValue: 0,
    soulbound: true,
  },
  unbroken_circle: {
    id: 'unbroken_circle',
    name: 'The Unbroken Circle',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 4, sta: 3 },
    pvpOffenseRating: 12,
    pvpDefenseRating: 12,
    priceHonor: 150,
    sellValue: 0,
    soulbound: true,
  },
  fleetblood_band: {
    id: 'fleetblood_band',
    name: 'Fleetblood Band',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 4, sta: 3 },
    pvpOffenseRating: 12,
    pvpDefenseRating: 12,
    priceHonor: 150,
    sellValue: 0,
    soulbound: true,
  },
  last_step_signet: {
    id: 'last_step_signet',
    name: 'Last-Step Signet',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 3, sta: 4 },
    pvpOffenseRating: 12,
    pvpDefenseRating: 12,
    priceHonor: 150,
    sellValue: 0,
    soulbound: true,
  },
  ashen_focus_ring: {
    id: 'ashen_focus_ring',
    name: 'Ashen Focus Ring',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 4, sta: 2, spi: 1 },
    pvpOffenseRating: 12,
    pvpDefenseRating: 12,
    priceHonor: 150,
    sellValue: 0,
    soulbound: true,
  },
  spellbreakers_seal: {
    id: 'spellbreakers_seal',
    name: "Spellbreaker's Seal",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 3, sta: 2, spi: 2 },
    pvpOffenseRating: 12,
    pvpDefenseRating: 12,
    priceHonor: 150,
    sellValue: 0,
    soulbound: true,
  },

  // Main hands: Strength, Agility, and caster profiles on the ilvl-28 DPS curve.
  final_argument_greatblade: {
    id: 'final_argument_greatblade',
    name: 'Final Argument Greatblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 34, max: 50, speed: 2.8 },
    stats: { str: 5, sta: 7 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  first_blood_razor: {
    id: 'first_blood_razor',
    name: 'First-Blood Razor',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 20, max: 31, speed: 1.7, dagger: true },
    stats: { agi: 5, sta: 7 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  emberglass_warstaff: {
    id: 'emberglass_warstaff',
    name: 'Emberglass Warstaff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 37, max: 54, speed: 3 },
    stats: { int: 6, sta: 4, spi: 2 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
};

export const FURY_STOCK: readonly string[] = Object.keys(WARFARE_ITEMS);

export const FURY_NPC: NpcDef = {
  id: FURY_NPC_ID,
  name: 'FURY',
  title: 'Honor Quartermaster',
  pos: { x: -11, z: 1 },
  facing: Math.PI / 2,
  color: 0xb52a2a,
  questIds: [],
  vendorItems: [...FURY_STOCK],
  dynamic: true,
  greeting: 'The sands remember every victory. Spend your honor well.',
};
