import type { AbilityDef } from '../types';

/** Retained Talents V2 active grants: Paladin, Hunter, Rogue, Priest, and Shaman. */
export const TALENT_ABILITIES_V2_A = {
  cleansing_verdict: {
    id: 'cleansing_verdict',
    name: 'Cleansing Verdict',
    class: 'paladin',
    learnLevel: 8,
    cost: 25,
    castTime: 0,
    cooldown: 8,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [
      { type: 'dispel', count: 1 },
      { type: 'heal', min: 40, max: 50 },
    ],
    description: 'Purges a harmful magic effect from a friendly target and heals them for $d Holy.',
  },
  holy_wrath: {
    id: 'holy_wrath',
    name: "Saint's Ire",
    class: 'paladin',
    learnLevel: 10,
    cost: 85,
    castTime: 0,
    cooldown: 20,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 54, max: 68, radius: 10 }],
    description: 'Unleashes holy power, damaging nearby enemies for $d. (Paladin talent)',
  },
  divine_shield: {
    id: 'divine_shield',
    name: 'Lightward',
    class: 'paladin',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 300,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'absorb', amount: 900, duration: 8 }],
    description: 'Shields you with holy power, absorbing 900 damage for 8 sec. (Paladin talent)',
  },
  avenging_wrath: {
    id: 'avenging_wrath',
    name: 'Wrathwing',
    class: 'paladin',
    learnLevel: 10,
    cost: 60,
    castTime: 0,
    cooldown: 180,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [
      { type: 'selfBuff', kind: 'buff_ap', value: 60, duration: 20 },
      { type: 'selfBuff', kind: 'buff_spellpower', value: 30, duration: 20 },
    ],
    description:
      'Calls down avenging power, increasing attack power by 60 and spell power by 30 for 20 sec. (Paladin talent)',
  },
  hammer_of_wrath: {
    id: 'hammer_of_wrath',
    name: 'Tolling Hammer',
    class: 'paladin',
    learnLevel: 10,
    cost: 65,
    castTime: 0,
    cooldown: 6,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    requiresTargetHpBelow: 0.2,
    effects: [{ type: 'directDamage', min: 110, max: 136 }],
    description:
      'Hurls a holy hammer at a wounded enemy for $d Holy damage. Only usable below 20% health. (Paladin talent)',
  },
  aura_surge: {
    id: 'aura_surge',
    name: 'Dawnward Ricochet',
    class: 'paladin',
    learnLevel: 20,
    cost: 55,
    castTime: 0,
    cooldown: 20,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    effects: [
      {
        type: 'chainDamage',
        min: 100,
        max: 120,
        jumps: 2,
        falloff: 0.75,
        radius: 10,
        hitsPrimary: true,
      },
      { type: 'silence', duration: 2 },
    ],
    description:
      'Hurl a dawnforged shield for $d Holy damage and silence the primary target for 2 sec. It bounces to up to 2 additional enemies within 10 yd for 75% damage per bounce. (Paladin talent)',
  },

  startle_shot: {
    id: 'startle_shot',
    name: 'Startle Shot',
    class: 'hunter',
    learnLevel: 8,
    cost: 25,
    castTime: 0,
    cooldown: 20,
    range: 35,
    minRange: 8,
    school: 'physical',
    scalesWith: 'ranged',
    requiresTarget: true,
    targetType: 'enemy',
    effects: [{ type: 'incapacitate', duration: 4 }],
    description: 'A wild shot that disorients the target for $t sec. Any damage breaks the effect.',
  },
  frost_trap: {
    id: 'frost_trap',
    name: 'Rime Snare',
    class: 'hunter',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'frost',
    requiresTarget: false,
    // A real trap (G6, combat/hunter_trap.ts): placed at the hunter's feet,
    // arms after 1.5 sec, freezes the FIRST enemy that touches it, one trap
    // at a time. Was a 30yd aimed 8yd-radius instant root+stun nova.
    effects: [
      {
        type: 'aoeRoot',
        duration: 3,
        radius: 3,
        min: 0,
        max: 0,
        stun: true,
        trap: { armTime: 1.5, lifetime: 60 },
      },
    ],
    description:
      'Places a frost trap at your feet that arms after 1.5 sec. The first enemy to touch it is frozen for 3 sec, unable to move or act. One trap at a time. Lasts 60 sec. (Hunter talent)',
  },
  multi_shot: {
    id: 'multi_shot',
    name: 'Splitshot',
    class: 'hunter',
    learnLevel: 10,
    cost: 55,
    castTime: 0,
    cooldown: 8,
    range: 35,
    minRange: 8,
    school: 'physical',
    scalesWith: 'ranged',
    requiresTarget: false,
    targetMode: 'position',
    effects: [{ type: 'aoeDamage', min: 62, max: 74, radius: 8 }],
    description:
      'Loose a spread at the target area, dealing $d Physical damage to enemies within 8 yd. (Hunter talent)',
  },
  deterrence: {
    id: 'deterrence',
    name: 'Bristleguard',
    class: 'hunter',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 300,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    // Balance pass round two (maintainer): 5 min cooldown and 25% dodge (the
    // 50pp wall on 2 min was too much); the all-school damage cut stays so it
    // still works against casters.
    effects: [
      { type: 'selfBuff', kind: 'buff_dodge', value: 0.25, duration: 10 },
      { type: 'selfBuff', kind: 'buff_dr', value: 0.3, duration: 10 },
    ],
    description:
      'Increases your dodge chance by 25 percentage points and reduces all damage taken by 30% for 10 sec. (Hunter talent)',
  },
  aspect_of_the_wild: {
    id: 'aspect_of_the_wild',
    name: 'Wildfang Rally',
    class: 'hunter',
    learnLevel: 10,
    cost: 50,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [
      { type: 'aoeAllyAttackPower', amount: 45, duration: 300, radius: 30 },
      { type: 'aoeAllyHaste', mult: 1.05, duration: 300, radius: 30 },
    ],
    description:
      'Inspires allies within 30 yd with wild strength, increasing attack power by 45 and attack speed by 5% for 5 min. (Hunter talent)',
  },

  smoke_screen: {
    id: 'smoke_screen',
    name: 'Smoke Screen',
    class: 'rogue',
    learnLevel: 8,
    cost: 25,
    castTime: 0,
    cooldown: 30,
    range: 0,
    requiresTarget: false,
    school: 'physical',
    effects: [{ type: 'selfBuff', kind: 'buff_dodge', value: 0.3, duration: 8 }],
    description: 'Vanish into a cloud of smoke, increasing your chance to dodge by 30% for 8 sec.',
  },
  preparation: {
    id: 'preparation',
    name: 'Contingency',
    class: 'rogue',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 300,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'clearCooldowns', abilities: ['sprint', 'evasion', 'vanish'] }],
    description: 'Finishes the cooldown on Swift Heels, Ghostfoot, and Smokestep. (Rogue talent)',
  },
  ghostly_strike: {
    id: 'ghostly_strike',
    name: 'Wraith Strike',
    class: 'rogue',
    learnLevel: 10,
    cost: 40,
    castTime: 0,
    cooldown: 20,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    awardsCombo: 1,
    effects: [
      { type: 'weaponStrike', bonus: 18 },
      { type: 'selfBuff', kind: 'buff_dodge', value: 0.15, duration: 7 },
    ],
    description:
      'Strikes the enemy for weapon damage plus $d and briefly increases dodge. Awards 1 combo point. (Rogue talent)',
  },
  cloak_of_shadows: {
    id: 'cloak_of_shadows',
    name: 'Shadecloak',
    class: 'rogue',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'absorb', amount: 420, duration: 5 }],
    description: 'Wraps you in shadows, absorbing 420 damage for 5 sec. (Rogue talent)',
  },
  shadowstep: {
    id: 'shadowstep',
    name: 'Shadeslip',
    class: 'rogue',
    learnLevel: 10,
    cost: 20,
    castTime: 0,
    cooldown: 24,
    range: 24,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'blinkForward', distance: 24 }],
    description:
      'Steps through the shadows toward your target without breaking Duskveil. (Rogue talent)',
  },

  silence: {
    id: 'silence',
    name: 'Hushword',
    class: 'priest',
    learnLevel: 10,
    cost: 55,
    castTime: 0,
    cooldown: 30,
    range: 30,
    school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'silence', duration: 4 }],
    description: 'Silences the target for 4 sec. (Priest talent)',
  },
  psychic_scream: {
    id: 'psychic_scream',
    name: 'Terror Canticle',
    class: 'priest',
    learnLevel: 10,
    cost: 45,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'aoeFear', duration: 4, radius: 8 }],
    description:
      'Frightens nearby enemies for up to 4 sec. Damage may break the effect. (Priest talent)',
  },
  inner_focus: {
    id: 'inner_focus',
    name: 'Stilled Mind',
    class: 'priest',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'next_cast_free', value: 1, duration: 60 }],
    description: 'Makes your next spell free. Lasts 60 sec. (Priest talent)',
  },
  desperate_prayer: {
    id: 'desperate_prayer',
    name: 'Last Prayer',
    class: 'priest',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'heal', min: 150, max: 185 }],
    description: 'Instantly heals you for $d. (Priest talent)',
  },
  prayer_of_healing: {
    id: 'prayer_of_healing',
    name: 'Choirmend',
    class: 'priest',
    learnLevel: 10,
    cost: 130,
    castTime: 3,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'aoeHeal', min: 100, max: 122, radius: 30 }],
    description: 'Heals nearby allies for $d. (Priest talent)',
  },
  mind_sear: {
    id: 'mind_sear',
    name: 'Thoughtburn',
    class: 'priest',
    learnLevel: 10,
    cost: 95,
    castTime: 0,
    channel: { duration: 3, ticks: 3 },
    cooldown: 0,
    range: 30,
    school: 'shadow',
    requiresTarget: false,
    targetMode: 'position',
    effects: [{ type: 'aoeDamage', min: 24, max: 28, radius: 8 }],
    description:
      'Channels shadow energy at the target area, damaging nearby enemies each second for $d. (Priest talent)',
  },

  healing_stream: {
    id: 'healing_stream',
    name: 'Springwell',
    class: 'shaman',
    learnLevel: 10,
    cost: 45,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'hot', total: 120, duration: 12, interval: 3 }],
    description: 'Restores 120 health to a friendly target over 12 sec. (Shaman talent)',
  },
  chain_lightning: {
    id: 'chain_lightning',
    name: 'Skybranch',
    class: 'shaman',
    learnLevel: 10,
    cost: 80,
    castTime: 2.5,
    cooldown: 6,
    range: 30,
    school: 'nature',
    requiresTarget: false,
    targetMode: 'position',
    effects: [{ type: 'aoeDamage', min: 70, max: 86, radius: 8 }],
    description:
      'Hurls lightning at the target area, damaging nearby enemies for $d. (Shaman talent)',
  },
  earthbind: {
    id: 'earthbind',
    name: 'Gripping Earth',
    class: 'shaman',
    learnLevel: 10,
    cost: 45,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'aoeRoot', duration: 2, radius: 8, min: 0, max: 0 }],
    description: 'Binds nearby enemies to the earth, rooting them for 2 sec. (Shaman talent)',
  },
  bloodlust: {
    id: 'bloodlust',
    name: 'Storm Chorus',
    class: 'shaman',
    learnLevel: 10,
    cost: 85,
    castTime: 0,
    cooldown: 300,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    // Full haste (attack, cast, and channel) to the group/raid, with the shared
    // exhaustion so it can never be chained with Temporal Acceleration (combat/
    // haste_burst.ts). Owner directive 2026-07-13: convert the shared effect to
    // full haste so caster/healer allies benefit, not only melee.
    effects: [
      {
        type: 'aoeAllyHaste',
        mult: 1.3,
        duration: 15,
        radius: 30,
        spell: true,
        exhaust: true,
        groupOnly: true,
      },
    ],
    description:
      'Whips your group or raid into a frenzy, increasing attack, casting, and channeling speed by 30% for 15 sec. Allies recently affected by Storm Chorus or Temporal Acceleration are too exhausted to benefit. (Shaman talent)',
  },
} satisfies Record<string, AbilityDef>;
