// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with `npm run wiki:content`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys, and rich spec/mastery prose resolves
// live through src/ui/talent_i18n.ts. No balance numbers or instanced spoilers here.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideAbilityRef { id: string; name: string; }
export interface GuideClassSpec { id: string; name: string; role: GuideRole; signature: string; }

// Interactive 3D model data, mirrored from the renderer's VisualDef manifest. The Guide's
// standalone viewer builds the model from one GLB on demand; entities reference a model by
// visual key into GUIDE_MODELS and carry their own tint color.
export interface GuideModelAttach { url: string; bone: string; position?: [number, number, number]; rotationY?: number; gripRef?: string; }
export interface GuideModelWeaponFix { node: string; rotX?: number; rotY?: number; rotZ?: number; }
export interface GuideModelSpec {
  url: string;
  idle: string | null;
  height: number;
  yaw?: number;
  hover?: number;
  show?: string[];
  attach?: GuideModelAttach[];
  weaponFix?: GuideModelWeaponFix[];
  tintStrength?: number;
}

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideAbilityRef[];
  abilities: GuideAbilityRef[];
  model: string;
  tint?: string;
}

export interface GuideZoneInfo {
  id: string;
  name: string;
  min: number;
  max: number;
  biome: string;
  hub: string;
  pois: string[];
  welcome: string;
}

export interface GuideDungeon {
  id: string;
  isRaid: boolean;
  suggestedPlayers: number;
  min: number | null;
  max: number | null;
  name?: string;
}

export interface GuideWarlockPet { id: string; name: string; model: string; tint?: string; }

export interface GuideCreature { name: string; min: number; max: number; rare: boolean; templateId: string; model: string; tint?: string; }
export interface GuideFamily { family: string; creatures: GuideCreature[]; }

export const GUIDE_CLASSES: GuideClassInfo[] = [
  {
    "id": "warrior",
    "color": "#c79c6e",
    "resource": "rage",
    "roles": [
      "tank",
      "dps"
    ],
    "specs": [
      {
        "id": "arms",
        "name": "Arms",
        "role": "dps",
        "signature": "mortal_strike"
      },
      {
        "id": "fury",
        "name": "Fury",
        "role": "dps",
        "signature": "bloodthirst"
      },
      {
        "id": "prot",
        "name": "Protection",
        "role": "tank",
        "signature": "shield_slam"
      }
    ],
    "signatureAbilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      }
    ],
    "abilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      },
      {
        "id": "hamstring",
        "name": "Hamstring"
      },
      {
        "id": "bloodrage",
        "name": "Bloodrage"
      },
      {
        "id": "overpower",
        "name": "Overpower"
      },
      {
        "id": "execute",
        "name": "Execute"
      },
      {
        "id": "slam",
        "name": "Slam"
      },
      {
        "id": "cleave",
        "name": "Cleave"
      },
      {
        "id": "defensive_stance",
        "name": "Defensive Stance"
      },
      {
        "id": "demoralizing_shout",
        "name": "Demoralizing Shout"
      },
      {
        "id": "sunder_armor",
        "name": "Sunder Armor"
      },
      {
        "id": "taunt",
        "name": "Taunt"
      }
    ],
    "model": "player_warrior"
  },
  {
    "id": "paladin",
    "color": "#f58cba",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "holy",
        "name": "Holy",
        "role": "healer",
        "signature": "flash_of_light"
      },
      {
        "id": "protection",
        "name": "Protection",
        "role": "tank",
        "signature": "righteous_fury"
      },
      {
        "id": "retribution",
        "name": "Retribution",
        "role": "dps",
        "signature": "judgement"
      }
    ],
    "signatureAbilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      }
    ],
    "abilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      },
      {
        "id": "hammer_of_justice",
        "name": "Hammer of Justice"
      },
      {
        "id": "lay_on_hands",
        "name": "Lay on Hands"
      },
      {
        "id": "flash_of_light",
        "name": "Flash of Light"
      },
      {
        "id": "exorcism",
        "name": "Exorcism"
      },
      {
        "id": "consecration",
        "name": "Consecration"
      },
      {
        "id": "righteous_fury",
        "name": "Righteous Fury"
      },
      {
        "id": "retribution_aura",
        "name": "Retribution Aura"
      }
    ],
    "model": "player_paladin"
  },
  {
    "id": "hunter",
    "color": "#abd473",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "beast_mastery",
        "name": "Beast Mastery",
        "role": "dps",
        "signature": "tame_beast"
      },
      {
        "id": "marksmanship",
        "name": "Marksmanship",
        "role": "dps",
        "signature": "aimed_shot"
      },
      {
        "id": "survival",
        "name": "Survival",
        "role": "dps",
        "signature": "wing_clip"
      }
    ],
    "signatureAbilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      }
    ],
    "abilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      },
      {
        "id": "wing_clip",
        "name": "Wing Clip"
      },
      {
        "id": "tame_beast",
        "name": "Tame Beast"
      },
      {
        "id": "dismiss_pet",
        "name": "Dismiss Pet"
      },
      {
        "id": "revive_pet",
        "name": "Revive Pet"
      },
      {
        "id": "aspect_of_the_monkey",
        "name": "Aspect of the Monkey"
      },
      {
        "id": "aspect_of_the_cheetah",
        "name": "Aspect of the Cheetah"
      },
      {
        "id": "aimed_shot",
        "name": "Aimed Shot"
      },
      {
        "id": "rapid_fire",
        "name": "Rapid Fire"
      }
    ],
    "model": "player_hunter"
  },
  {
    "id": "rogue",
    "color": "#fff569",
    "resource": "energy",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "assassination",
        "name": "Assassination",
        "role": "dps",
        "signature": "eviscerate"
      },
      {
        "id": "combat",
        "name": "Combat",
        "role": "dps",
        "signature": "adrenaline_rush"
      },
      {
        "id": "subtlety",
        "name": "Subtlety",
        "role": "dps",
        "signature": "ambush"
      }
    ],
    "signatureAbilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      }
    ],
    "abilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      },
      {
        "id": "evasion",
        "name": "Evasion"
      },
      {
        "id": "sap",
        "name": "Sap"
      },
      {
        "id": "slice_and_dice",
        "name": "Slice and Dice"
      },
      {
        "id": "sprint",
        "name": "Sprint"
      },
      {
        "id": "crippling_poison",
        "name": "Crippling Poison"
      },
      {
        "id": "kidney_shot",
        "name": "Kidney Shot"
      },
      {
        "id": "expose_armor",
        "name": "Expose Armor"
      },
      {
        "id": "ambush",
        "name": "Ambush"
      },
      {
        "id": "rupture",
        "name": "Rupture"
      },
      {
        "id": "vanish",
        "name": "Vanish"
      },
      {
        "id": "instant_poison",
        "name": "Instant Poison"
      },
      {
        "id": "adrenaline_rush",
        "name": "Adrenaline Rush"
      },
      {
        "id": "deadly_poison",
        "name": "Deadly Poison"
      },
      {
        "id": "blind",
        "name": "Blind"
      },
      {
        "id": "stealth",
        "name": "Stealth"
      }
    ],
    "model": "player_rogue"
  },
  {
    "id": "priest",
    "color": "#fffff0",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "discipline",
        "name": "Discipline",
        "role": "healer",
        "signature": "power_word_shield"
      },
      {
        "id": "holy",
        "name": "Holy",
        "role": "healer",
        "signature": "flash_heal"
      },
      {
        "id": "shadow",
        "name": "Shadow",
        "role": "dps",
        "signature": "mind_flay"
      }
    ],
    "signatureAbilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      }
    ],
    "abilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      },
      {
        "id": "mind_blast",
        "name": "Mind Blast"
      },
      {
        "id": "heal",
        "name": "Heal"
      },
      {
        "id": "mind_flay",
        "name": "Mind Flay"
      },
      {
        "id": "flash_heal",
        "name": "Flash Heal"
      }
    ],
    "model": "player_priest",
    "tint": "#f0e9d6"
  },
  {
    "id": "shaman",
    "color": "#0070de",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "elemental",
        "name": "Elemental",
        "role": "dps",
        "signature": "lightning_bolt"
      },
      {
        "id": "enhancement",
        "name": "Enhancement",
        "role": "dps",
        "signature": "stormstrike"
      },
      {
        "id": "restoration",
        "name": "Restoration",
        "role": "healer",
        "signature": "healing_wave"
      }
    ],
    "signatureAbilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      }
    ],
    "abilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      },
      {
        "id": "flametongue_weapon",
        "name": "Flametongue Weapon"
      },
      {
        "id": "frost_shock",
        "name": "Frost Shock"
      },
      {
        "id": "frostbrand_weapon",
        "name": "Frostbrand Weapon"
      },
      {
        "id": "ghost_wolf",
        "name": "Ghost Wolf"
      },
      {
        "id": "stormstrike",
        "name": "Stormstrike"
      }
    ],
    "model": "player_shaman",
    "tint": "#6f8fc9"
  },
  {
    "id": "mage",
    "color": "#69ccf0",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "arcane",
        "name": "Arcane",
        "role": "dps",
        "signature": "arcane_missiles"
      },
      {
        "id": "fire",
        "name": "Fire",
        "role": "dps",
        "signature": "scorch"
      },
      {
        "id": "frost",
        "name": "Frost",
        "role": "dps",
        "signature": "ice_barrier"
      }
    ],
    "signatureAbilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      }
    ],
    "abilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      },
      {
        "id": "fire_blast",
        "name": "Fire Blast"
      },
      {
        "id": "arcane_missiles",
        "name": "Arcane Missiles"
      },
      {
        "id": "polymorph",
        "name": "Polymorph"
      },
      {
        "id": "frost_nova",
        "name": "Frost Nova"
      },
      {
        "id": "arcane_explosion",
        "name": "Arcane Explosion"
      },
      {
        "id": "scorch",
        "name": "Scorch"
      },
      {
        "id": "ice_barrier",
        "name": "Ice Barrier"
      },
      {
        "id": "pyroblast",
        "name": "Pyroblast"
      }
    ],
    "model": "player_mage"
  },
  {
    "id": "warlock",
    "color": "#9482c9",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "affliction",
        "name": "Affliction",
        "role": "dps",
        "signature": "drain_life"
      },
      {
        "id": "demonology",
        "name": "Demonology",
        "role": "dps",
        "signature": "demon_skin"
      },
      {
        "id": "destruction",
        "name": "Destruction",
        "role": "dps",
        "signature": "shadowburn"
      }
    ],
    "signatureAbilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      }
    ],
    "abilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      },
      {
        "id": "summon_voidwalker",
        "name": "Summon Voidwalker"
      },
      {
        "id": "curse_of_agony",
        "name": "Curse of Agony"
      },
      {
        "id": "drain_life",
        "name": "Drain Life"
      },
      {
        "id": "fear",
        "name": "Fear"
      },
      {
        "id": "searing_pain",
        "name": "Searing Pain"
      },
      {
        "id": "shadowburn",
        "name": "Shadowburn"
      },
      {
        "id": "summon_succubus",
        "name": "Summon Succubus"
      },
      {
        "id": "summon_felhunter",
        "name": "Summon Felhunter"
      },
      {
        "id": "summon_felguard",
        "name": "Summon Felguard"
      },
      {
        "id": "summon_infernal",
        "name": "Summon Infernal"
      },
      {
        "id": "summon_doomguard",
        "name": "Summon Doomguard"
      }
    ],
    "model": "player_warlock",
    "tint": "#8d5fd3"
  },
  {
    "id": "druid",
    "color": "#ff7d0a",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "balance",
        "name": "Balance",
        "role": "dps",
        "signature": "starfire"
      },
      {
        "id": "feral",
        "name": "Feral",
        "role": "tank",
        "signature": "bear_form"
      },
      {
        "id": "restoration",
        "name": "Restoration",
        "role": "healer",
        "signature": "regrowth"
      }
    ],
    "signatureAbilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      }
    ],
    "abilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      },
      {
        "id": "entangling_roots",
        "name": "Entangling Roots"
      },
      {
        "id": "bear_form",
        "name": "Bear Form"
      },
      {
        "id": "bear_charge",
        "name": "Bear Charge"
      },
      {
        "id": "maul",
        "name": "Maul"
      },
      {
        "id": "growl",
        "name": "Growl"
      },
      {
        "id": "demoralizing_roar",
        "name": "Demoralizing Roar"
      },
      {
        "id": "cat_form",
        "name": "Wolf Form"
      },
      {
        "id": "prowl",
        "name": "Prowl"
      },
      {
        "id": "rake",
        "name": "Rake"
      },
      {
        "id": "claw",
        "name": "Claw"
      },
      {
        "id": "regrowth",
        "name": "Regrowth"
      },
      {
        "id": "ferocious_bite",
        "name": "Ferocious Bite"
      },
      {
        "id": "barkskin",
        "name": "Barkskin"
      },
      {
        "id": "swipe",
        "name": "Swipe"
      },
      {
        "id": "starfire",
        "name": "Starfire"
      },
      {
        "id": "travel_form",
        "name": "Travel Form"
      },
      {
        "id": "enrage",
        "name": "Enrage"
      },
      {
        "id": "bash",
        "name": "Bash"
      },
      {
        "id": "faerie_fire",
        "name": "Faerie Fire"
      },
      {
        "id": "hibernate",
        "name": "Hibernate"
      },
      {
        "id": "dash",
        "name": "Dash"
      },
      {
        "id": "pounce",
        "name": "Pounce"
      },
      {
        "id": "insect_swarm",
        "name": "Insect Swarm"
      },
      {
        "id": "tigers_fury",
        "name": "Tiger's Fury"
      },
      {
        "id": "rip",
        "name": "Rip"
      }
    ],
    "model": "player_druid"
  }
];

export const GUIDE_ZONES: GuideZoneInfo[] = [
  {
    "id": "eastbrook_vale",
    "name": "Eastbrook Vale",
    "min": 1,
    "max": 7,
    "biome": "vale",
    "hub": "Eastbrook",
    "pois": [
      "Eastbrook",
      "Wolf Run",
      "Boar Meadow",
      "Mirror Lake",
      "Webwood",
      "Copper Dig",
      "Bandit Camp",
      "Fallen Chapel",
      "Brightwood Glade"
    ],
    "welcome": "Find Marshal Redbrook in town — he has work for you."
  },
  {
    "id": "mirefen_marsh",
    "name": "Mirefen Marsh",
    "min": 6,
    "max": 13,
    "biome": "marsh",
    "hub": "Fenbridge",
    "pois": [
      "Fenbridge",
      "Prowler Reeds",
      "Deepfen Shallows",
      "Widow Thicket",
      "Drowned Chapel",
      "Troll Mounds",
      "Gravecaller Encampment",
      "The Sunken Bastion"
    ],
    "welcome": "Report to Warden Fenwick at the Fenbridge gate."
  },
  {
    "id": "thornpeak_heights",
    "name": "Thornpeak Heights",
    "min": 13,
    "max": 20,
    "biome": "peaks",
    "hub": "Highwatch",
    "pois": [
      "Highwatch",
      "Stalker Ridge",
      "Deeprock Burrows",
      "Ogre Foothills",
      "Drogmar's War-Camp",
      "Stormcrag",
      "The Glimmermere",
      "Wyrmcult Tents",
      "Revenant Fields",
      "Gravewyrm Sanctum"
    ],
    "welcome": "Captain Thessaly holds the wall at Highwatch — barely."
  }
];

export const GUIDE_DUNGEONS: GuideDungeon[] = [
  {
    "id": "hollow_crypt",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 7,
    "max": 10,
    "name": "The Hollow Crypt"
  },
  {
    "id": "sunken_bastion",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 12,
    "max": 13,
    "name": "The Sunken Bastion"
  },
  {
    "id": "drowned_temple",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 16,
    "max": 18,
    "name": "The Drowned Temple"
  },
  {
    "id": "gravewyrm_sanctum",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 19,
    "max": 20,
    "name": "Gravewyrm Sanctum"
  },
  {
    "id": "raid",
    "isRaid": true,
    "suggestedPlayers": 10,
    "min": 20,
    "max": 20
  }
];

export const GUIDE_WARLOCK_PETS: GuideWarlockPet[] = [
  {
    "id": "imp",
    "name": "Imp",
    "model": "mob_demon",
    "tint": "#ff7a2a"
  },
  {
    "id": "voidwalker",
    "name": "Voidwalker",
    "model": "mob_demon",
    "tint": "#3a3a6e"
  },
  {
    "id": "succubus",
    "name": "Succubus",
    "model": "mob_demon",
    "tint": "#c6469b"
  },
  {
    "id": "felhunter",
    "name": "Felhunter",
    "model": "mob_demonalt",
    "tint": "#4a7d4a"
  },
  {
    "id": "felguard",
    "name": "Felguard",
    "model": "mob_demonalt",
    "tint": "#6e5a2a"
  },
  {
    "id": "infernal",
    "name": "Infernal",
    "model": "mob_demonalt",
    "tint": "#d24a2a"
  },
  {
    "id": "doomguard",
    "name": "Doomguard",
    "model": "mob_demonalt",
    "tint": "#7a3a8e"
  }
];

export const GUIDE_FAMILIES: GuideFamily[] = [
  {
    "family": "beast",
    "creatures": [
      {
        "name": "Brightwood Hare",
        "min": 1,
        "max": 2,
        "rare": false,
        "templateId": "brightwood_hare",
        "model": "mob_critter",
        "tint": "#c8a972"
      },
      {
        "name": "Forest Wolf",
        "min": 1,
        "max": 2,
        "rare": false,
        "templateId": "forest_wolf",
        "model": "mob_wolf",
        "tint": "#7f8c8d"
      },
      {
        "name": "Glade Fox",
        "min": 2,
        "max": 3,
        "rare": false,
        "templateId": "glade_fox",
        "model": "mob_fox",
        "tint": "#d2691e"
      },
      {
        "name": "Spotted Fawn",
        "min": 2,
        "max": 3,
        "rare": false,
        "templateId": "spotted_fawn",
        "model": "mob_stag",
        "tint": "#b5895f"
      },
      {
        "name": "Wild Boar",
        "min": 2,
        "max": 3,
        "rare": false,
        "templateId": "wild_boar",
        "model": "mob_boar",
        "tint": "#935116"
      },
      {
        "name": "Dawnmane Doe",
        "min": 3,
        "max": 4,
        "rare": false,
        "templateId": "dawnmane_doe",
        "model": "mob_stag",
        "tint": "#a9763f"
      },
      {
        "name": "Meadow Crane",
        "min": 3,
        "max": 4,
        "rare": false,
        "templateId": "meadow_crane",
        "model": "mob_wolf",
        "tint": "#eaeaea"
      },
      {
        "name": "Thornpelt Badger",
        "min": 3,
        "max": 4,
        "rare": false,
        "templateId": "thornpelt_badger",
        "model": "mob_critter",
        "tint": "#5d5d5d"
      },
      {
        "name": "Bramble Lynx",
        "min": 4,
        "max": 5,
        "rare": false,
        "templateId": "bramble_lynx",
        "model": "mob_wolf",
        "tint": "#8a6d3b"
      },
      {
        "name": "Brightwood Stag",
        "min": 4,
        "max": 5,
        "rare": false,
        "templateId": "brightwood_stag",
        "model": "mob_stag",
        "tint": "#946638"
      },
      {
        "name": "Old Greyjaw",
        "min": 4,
        "max": 4,
        "rare": true,
        "templateId": "old_greyjaw",
        "model": "mob_wolf",
        "tint": "#566061"
      },
      {
        "name": "Grovetusk Boar",
        "min": 5,
        "max": 6,
        "rare": false,
        "templateId": "grovetusk_boar",
        "model": "mob_boar",
        "tint": "#6b4423"
      },
      {
        "name": "Sunhide Bear",
        "min": 5,
        "max": 6,
        "rare": false,
        "templateId": "sunhide_bear",
        "model": "mob_bear",
        "tint": "#5a4030"
      },
      {
        "name": "Mire Prowler",
        "min": 7,
        "max": 8,
        "rare": false,
        "templateId": "mire_prowler",
        "model": "mob_wolf",
        "tint": "#4d5656"
      },
      {
        "name": "Bog Bloat",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "bog_bloat",
        "model": "mob_murloc",
        "tint": "#6b8e23"
      },
      {
        "name": "Ridge Stalker",
        "min": 13,
        "max": 14,
        "rare": false,
        "templateId": "ridge_stalker",
        "model": "mob_wolf",
        "tint": "#8c8270"
      }
    ]
  },
  {
    "family": "spider",
    "creatures": [
      {
        "name": "Webwood Lurker",
        "min": 2,
        "max": 4,
        "rare": false,
        "templateId": "webwood_spider",
        "model": "mob_spider",
        "tint": "#4a235a"
      },
      {
        "name": "Sableweb Hatchling",
        "min": 5,
        "max": 5,
        "rare": false,
        "templateId": "sableweb_hatchling",
        "model": "mob_spider",
        "tint": "#21112d"
      },
      {
        "name": "Mirefen Widow",
        "min": 8,
        "max": 10,
        "rare": false,
        "templateId": "mire_widow",
        "model": "mob_spider",
        "tint": "#283747"
      }
    ]
  },
  {
    "family": "murloc",
    "creatures": [
      {
        "name": "Mudfin Skulker",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "mudfin_murloc",
        "model": "mob_murloc",
        "tint": "#52be80"
      },
      {
        "name": "Deepfen Snapper",
        "min": 8,
        "max": 9,
        "rare": false,
        "templateId": "deepfen_murloc",
        "model": "mob_murloc",
        "tint": "#45b39d"
      },
      {
        "name": "Mirejaw Frenzy",
        "min": 9,
        "max": 10,
        "rare": false,
        "templateId": "mirejaw_frenzy",
        "model": "mob_murloc",
        "tint": "#1abc9c"
      }
    ]
  },
  {
    "family": "kobold",
    "creatures": [
      {
        "name": "Tunnel Rat Digger",
        "min": 4,
        "max": 6,
        "rare": false,
        "templateId": "tunnel_rat",
        "model": "mob_kobold",
        "tint": "#9c640c"
      },
      {
        "name": "Deeprock Tunneler",
        "min": 14,
        "max": 15,
        "rare": false,
        "templateId": "deeprock_kobold",
        "model": "mob_kobold",
        "tint": "#9c7a3c"
      },
      {
        "name": "Ironvein Sapper",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "ironvein_sapper",
        "model": "mob_kobold",
        "tint": "#8f6b34"
      }
    ]
  },
  {
    "family": "humanoid",
    "creatures": [
      {
        "name": "Vale Bandit",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "vale_bandit",
        "model": "mob_bandit",
        "tint": "#6b3a32"
      },
      {
        "name": "Mogger Lackey",
        "min": 5,
        "max": 6,
        "rare": false,
        "templateId": "mogger_lackey",
        "model": "mob_bandit",
        "tint": "#6b3a32"
      },
      {
        "name": "Gravecaller Cultist",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_cultist",
        "model": "mob_dark_caster",
        "tint": "#6c3483"
      },
      {
        "name": "Gravecaller Mender",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_mender",
        "model": "mob_bandit",
        "tint": "#6b3a32"
      },
      {
        "name": "Gravecaller Summoner",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_summoner",
        "model": "mob_dark_caster",
        "tint": "#884ea0"
      },
      {
        "name": "Nhalia Mourner",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "nhalia_mourner",
        "model": "mob_bandit",
        "tint": "#6b3a32"
      },
      {
        "name": "Wyrmcult Zealot",
        "min": 17,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_zealot",
        "model": "mob_bandit",
        "tint": "#6b3a32"
      },
      {
        "name": "Wyrmcult Necromancer",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_necromancer",
        "model": "mob_dark_caster",
        "tint": "#533566"
      }
    ]
  },
  {
    "family": "troll",
    "creatures": [
      {
        "name": "Mirefen Troll",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "fen_troll",
        "model": "mob_troll",
        "tint": "#229954"
      },
      {
        "name": "Grubjaw the Glutton",
        "min": 12,
        "max": 12,
        "rare": true,
        "templateId": "grubjaw",
        "model": "mob_troll",
        "tint": "#145a32"
      }
    ]
  },
  {
    "family": "ogre",
    "creatures": [
      {
        "name": "Thornpeak Ogre",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "thornpeak_ogre",
        "model": "mob_ogre",
        "tint": "#9e7b53"
      }
    ]
  },
  {
    "family": "undead",
    "creatures": [
      {
        "name": "Restless Bones",
        "min": 5,
        "max": 7,
        "rare": false,
        "templateId": "restless_bones",
        "model": "skel_minion",
        "tint": "#d5dbdb"
      },
      {
        "name": "Drowned Dead",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "drowned_dead",
        "model": "skel_minion",
        "tint": "#7fb3d5"
      },
      {
        "name": "Boneclad Revenant",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "boneclad_revenant",
        "model": "skel_warrior",
        "tint": "#cacfd2"
      },
      {
        "name": "Varkas Boneguard",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "varkas_boneguard",
        "model": "skel_minion",
        "tint": "#c9c2b5"
      }
    ]
  },
  {
    "family": "elemental",
    "creatures": [
      {
        "name": "Stormcrag Elemental",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "stormcrag_elemental",
        "model": "mob_elemental",
        "tint": "#5dade2"
      },
      {
        "name": "Shardlord Kazzix",
        "min": 18,
        "max": 18,
        "rare": true,
        "templateId": "shardlord_kazzix",
        "model": "mob_elemental",
        "tint": "#aed6f1"
      }
    ]
  }
];

export const GUIDE_MODELS: Record<string, GuideModelSpec> = {
  "player_warrior": {
    "url": "models/chars/players/knight.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Knight_Helmet",
      "Knight_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/sword_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_paladin": {
    "url": "models/chars/players/paladin.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_hunter": {
    "url": "models/chars/players/ranger.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/crossbow_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_rogue": {
    "url": "models/chars/players/rogue.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Rogue_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ]
  },
  "player_priest": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "player_shaman": {
    "url": "models/chars/players/barbarian.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Barbarian_BearHat"
    ],
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.4
  },
  "player_mage": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_warlock": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/wand.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/spellbook_open.glb",
        "bone": "handslot.l",
        "gripRef": "Spellbook_open"
      }
    ],
    "tintStrength": 0.45
  },
  "player_druid": {
    "url": "models/chars/players/druid.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "mob_demon": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 1.8,
    "tintStrength": 0.5
  },
  "mob_demonalt": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.35
  },
  "mob_wolf": {
    "url": "models/creatures/wolf.glb",
    "idle": "Idle",
    "height": 1.6,
    "tintStrength": 0.35
  },
  "mob_boar": {
    "url": "models/creatures/wild_boar.glb",
    "idle": "Idle1",
    "height": 1.45,
    "tintStrength": 0.4
  },
  "mob_spider": {
    "url": "models/creatures/spider.glb",
    "idle": "Spider_Idle",
    "height": 1.4,
    "tintStrength": 0.35
  },
  "mob_bandit": {
    "url": "models/chars/players/rogue_hooded.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ],
    "tintStrength": 0.3
  },
  "mob_murloc": {
    "url": "models/creatures/frog.glb",
    "idle": "Idle",
    "height": 1.7,
    "tintStrength": 0.45
  },
  "mob_kobold": {
    "url": "models/creatures/goblin.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.2
  },
  "skel_minion": {
    "url": "models/chars/enemies/skeleton_minion.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "mob_critter": {
    "url": "models/creatures/fox.glb",
    "idle": "Idle",
    "height": 0.7,
    "tintStrength": 0.35
  },
  "mob_fox": {
    "url": "models/creatures/fox.glb",
    "idle": "Idle",
    "height": 1,
    "tintStrength": 0.35
  },
  "mob_stag": {
    "url": "models/creatures/stag.glb",
    "idle": "Idle",
    "height": 1.9,
    "tintStrength": 0.35
  },
  "mob_bear": {
    "url": "models/creatures/yetialt.glb",
    "idle": "Idle",
    "height": 2.2,
    "tintStrength": 0.5
  },
  "mob_troll": {
    "url": "models/creatures/orc.glb",
    "idle": "Idle",
    "height": 2.4,
    "tintStrength": 0.12
  },
  "mob_dark_caster": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Hat"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "mob_ogre": {
    "url": "models/creatures/giant.glb",
    "idle": "Idle",
    "height": 2.8,
    "tintStrength": 0.2
  },
  "mob_elemental": {
    "url": "models/creatures/golelingevolved.glb",
    "idle": "Flying_Idle",
    "height": 2.2,
    "hover": 0.3,
    "tintStrength": 0.4
  },
  "skel_warrior": {
    "url": "models/chars/enemies/skeleton_warrior.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  }
};
